// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH02zNtotNGWVH6qplnoWqElvxdS5YFHU',
    appId: '1:542587672640:android:b34bb1f5280115b055e7a5',
    messagingSenderId: '542587672640',
    projectId: 'time-tracker-flutter-477b3',
    storageBucket: 'time-tracker-flutter-477b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzUWsYptLAb9UMxacQ3qyNH5_lsUGv81I',
    appId: '1:542587672640:ios:2b40b0be523b4a2c55e7a5',
    messagingSenderId: '542587672640',
    projectId: 'time-tracker-flutter-477b3',
    storageBucket: 'time-tracker-flutter-477b3.appspot.com',
    androidClientId: '542587672640-19hvvle7m2b4uqqoosbatclc7acnooro.apps.googleusercontent.com',
    iosClientId: '542587672640-rke56hcqlcn4kgs41ppasht20co4mfhg.apps.googleusercontent.com',
    iosBundleId: 'com.fiixed.timeTrackerFlutter',
  );
}
